from __future__ import annotations

from pathlib import Path
from typing import Optional, Tuple
# 参数配置文件
YANJIUYUAN_DIR = Path(__file__).resolve().parent
MODEL_DIR = YANJIUYUAN_DIR / "models"
BOX_MODEL_PATH = MODEL_DIR / "box.STL"
BOX_TEMPLATE_PLY = MODEL_DIR / "box_z_parallel_surface_points.ply"
BOX_CAPTURE_ROOT = YANJIUYUAN_DIR / "captures"

# Default world-frame bottle place goal used by the offline ICP -> pick-and-place scripts.
# Tune this when you want to put the placed bottle closer to/farther from the robot.
BOTTLE_ROBOT_SIDE_PLACE_POS = (0.2, -0.5, 0.15)

Range3D = Optional[Tuple[Optional[float], Optional[float]]]

# Box template generation used by sample_box_surface.py.
BOX_TEMPLATE_N_SAMPLES = 10000
BOX_TEMPLATE_NORMAL_Z_TOLERANCE = 1e-6
BOX_TEMPLATE_SURFACE_Z_MIN = 0.21
BOX_TEMPLATE_INCLUDE_NORMALS = True
BOX_TEMPLATE_CENTER_BOTTOM = False
BOX_TEMPLATE_RANDOM_SEED: Optional[int] = 0

# Target preprocessing used by box_icp_from_saved_capture.py.
BOX_USE_BLUE_RGB_SEGMENTATION = True
BOX_BLUE_HUE_RANGE_DEG = (170.0, 280.0)
BOX_BLUE_MIN_SATURATION = 0.08
BOX_BLUE_MIN_VALUE = 0.02
BOX_BLUE_DOMINANCE_MARGIN = 0.0
# 箱子点云过滤范围
BOX_X_RANGE: Range3D = (0.40, 1.05) # 箱子长0.6m
BOX_Y_RANGE: Range3D = (-0.35, 0.35)    # 箱子宽0.4m
BOX_Z_RANGE: Range3D = (0.02, 0.35) # 箱子高0.23m
BOX_TARGET_VOXEL_DOWNSAMPLE = 0.008
BOX_MATCH_TARGET_Z_MIN = 0.21
BOX_MATCH_TARGET_Z_MAX = 0.24

BOX_KEEP_LARGEST_BLUE_CLUSTER = False
BOX_BLUE_CLUSTER_EPS = 0.035
BOX_BLUE_CLUSTER_MIN_POINTS = 80
BOX_REMOVE_STATISTICAL_OUTLIERS = False
BOX_OUTLIER_NB_NEIGHBORS = 30
BOX_OUTLIER_STD_RATIO = 2.0

# Registration settings.
BOX_REGISTRATION_VOXEL_SIZE = 0.02
BOX_TEMPLATE_TOP_Z_MIN = BOX_TEMPLATE_SURFACE_Z_MIN
BOX_TEMPLATE_NORMAL_Z_ABS_MIN = 0.95
BOX_OBB_LONG_SHORT_MIN_RATIO = 1.05
BOX_OBB_REQUIRE_LONG_SHORT_RATIO = False
BOX_OBB_HORIZONTAL_AXIS_MIN_NORM = 0.25
BOX_ICP_MAX_ITERATION = 40

# Output, viewer, and progress settings.
BOX_OUTPUT_DIR = None
BOX_SHOW_RESULT_VIEWER = True
BOX_TARGET_POINT_SIZE = 0.002
BOX_MODEL_POINT_SIZE = 0.003
BOX_FINAL_TARGET_VOXEL_DOWNSAMPLE = 0.006
BOX_FINAL_MODEL_VOXEL_DOWNSAMPLE = 0.006
BOX_WRITE_DEBUG_POINTCLOUDS = True
BOX_LOG_STEPS = True
BOX_OPEN3D_PRINT_PROGRESS = False
# Object extraction inside the detected box.
BOX_OBJECT_OUTPUT_DIR = None
BOX_OBJECT_INNER_XY_MARGIN = 0.0
BOX_OBJECT_CONCAVE_X_RANGE = (-0.27, 0.27)
BOX_OBJECT_CONCAVE_Y_RANGE = (-0.16, 0.16)
BOX_OBJECT_CONCAVE_Z_RANGE = (0.03, 0.26)
BOX_OBJECT_CONCAVE_REGION_RGB = (0.0, 0.75, 1.0)
BOX_OBJECT_TOP_OVERHANG_XY_MARGIN = 0.045
BOX_OBJECT_ABOVE_TOP_MARGIN = 0.12
BOX_OBJECT_REMOVE_BLUE_BOX_POINTS = False
BOX_OBJECT_SHOW_REMOVED_CONTEXT = True
BOX_OBJECT_REMOVED_CONTEXT_XY_MARGIN = 0.08
BOX_OBJECT_REMOVED_CONTEXT_Z_MARGIN = 0.04
BOX_OBJECT_AUTO_SEGMENT_BOX = False
BOX_OBJECT_PIXEL_COLOR_TOLERANCE = 2
BOX_OBJECT_PIXEL_MAPPING_MIN_RATIO = 0.70
BOX_OBJECT_CANDIDATE_VOXEL_DOWNSAMPLE = 0.003
BOX_OBJECT_REMOVED_VOXEL_DOWNSAMPLE = 0.006
BOX_OBJECT_SELECTED_VOXEL_DOWNSAMPLE = 0.003
BOX_OBJECT_SHOW_VIEWER = True
BOX_OBJECT_SHOW_BOX_MODEL = False
BOX_OBJECT_POINT_SIZE = 0.002
